site_name: moe-parsers documentation
site_author: nichind
site_description: >-
  Parsing anime and getting video made easy

repo_name: nichind/moe-parsers
repo_url: https://github.com/nichind/moe-parsers

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - content.code.annotate
    - content.tooltips

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home:
    - Index: index.md