name: Run Tests

on:  
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest\

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt 
          pip install pytest==8.3.4
          pip install pytest-cov==6.0.0
          pip install pytest-asyncio

      - name: Run Tests
        run: |
          PYTHONPATH=. pytest tests/ --tb=short --disable-warnings
